Directory clean up
ScienceCore/climaterisk pull request #70
Opened 2024-06-03 00:35 UTC by JFormoso

- Changed all .ipynb and .py files to .md.
- Organized the directory based on @dhavide indications. 
- Corrected paths to images.

2024-06-03 14:10 UTC, jnywong requested changes

2024-06-03 14:10 UTC, jnywong commented on book/.netrc
We should keep this file as a template for users to store credentials to access NASA Earthdata.

2024-06-03 19:06 UTC, JFormoso commented on book/09_Scratch/intro.md
> Is this file the homepage for the Jupyter Book website? If so, I propose to move this to `book/intro.md`.

I don't know what this file is, it does not have much. It may be a leftover from a previous iteration. I'll ask at Friday's meeting.

2024-06-03 19:08 UTC, JFormoso commented on book/.netrc
I'll add it to the NASA Earthdata folder.

2024-06-03 19:16 UTC, JFormoso commented
@jnywong thank you for taking the time to look at this. I think I made all the changes you suggested.

2024-06-05 10:12 UTC, JFormoso commented
Hello, for some reason I cannot merge this pull request, it does not give me the option. Can you @jnywong or @dhavide do it? Or let me know what I am doing wrong?

2024-06-05 10:12 UTC, merged